### ISSUE TITLE
Maximum graph size

### ISSUE THREAD

**Issue by davidcmh** [anvaka/ngraph.native#1]
Hi Andrei, I am currently doing a academic project on graph visualization and I am planning to implement force-directed layout on multiple large graph datasets. Just wondering, what is the biggest graph you have tried processing with this C++ algorithm? What do you think is its limit?

Cheers,
David

**Comment by anvaka** [comment]
4 million nodes, 30+ million edges was the largest so far.

Have you looked at sfdp from graphviz? I know in theory it can layout hundreds of millions nodes graph (yet I couldn't get it to work on one million nodes on practice, but probably I was doing something wrong)
